# -*- coding: utf-8 -*-
"""eikonal_routines.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sd4r9GlwxHjw5LBjQCXKXWnzJ0TltMYW
"""

import numpy as np

def update_eikonal_2D(i, j, u, F, h, N):
    # LEFTMOST OR RIGHTMOST BORDERS
    if i == 0:
        a = u[i + 1, j]
    elif i == N - 1:
        a = u[i - 1, j]
    else:
        a = min(u[i + 1, j], u[i - 1, j])

    # UPPERMOST OR LOWERMOST BORDERS
    if j == 0:
        b = u[i, j + 1]
    elif j == N - 1:
        b = u[i, j - 1]
    else:
        b = min(u[i, j + 1], u[i, j - 1])

    # EIKONAL UPDATE
    if abs(a - b) < h * F[i, j]:
        u_new = 0.5 * (a + b + np.sqrt((2 * (h * F[i, j]) ** 2) - (a - b) ** 2))
    else:
        u_new = h * F[i, j] + min(a, b)

    return min(u[i, j], u_new)
